### ISSUE TITLE
tfcoreml dependency issue

### ISSUE THREAD

**Issue by fahadchauhan4** [gouthamvgk/facemesh_coreml_tf#2]
Hello, I am trying to run the convert_blazeface.py file and it needs tfcoreml package which isn't mentioned in the requirements but when i install it using "pip install tfcoreml" it starts installing tf1.14 as a pre-requirement for tfcoreml. but your repo requirements, tf version 2.2 is mentioned. what to do?

**Comment by gouthamvgk** [comment]
It seems the code of tfcoreml has changed after this repo has been last updated. Install tfcormel using the following command "pip install git+git://github.com/tf-coreml/tf-coreml.git@03eac3145328b113458b9989306ee4a67b9e66b1" . This should install the required version that works with tf==2.2.0 and coremltools==3.4
